hash-format = "sha256"

[[files]]
file = "README.MD"
hash = "61aca620f38929ecd9f02d45fc3ac5d9979754e6040bf9295731284514db340d"

[[files]]
file = "config/yosbr/config/bobby.conf"
hash = "c1c410217d8d303226b7944983359db758a9d28eec0087e34e7f79eecae0e97e"

[[files]]
file = "config/yosbr/config/fog/config.json"
hash = "c732dc6fe1418844dbbe794ad8a94cd5016b8d8072a456721154ba2851478925"

[[files]]
file = "config/yosbr/config/xaerominimap-common.txt"
hash = "771a844d13ab6c2ff99f14b8fd912d02c55a1a4104361692b740c3e596084f6f"

[[files]]
file = "config/yosbr/config/xaerominimap.txt"
hash = "b79c2e018fbe5ec437de6b37fc0aec105d542e4459b196fc85b9718acf0e9525"

[[files]]
file = "config/yosbr/config/xaerominimap_entities.json"
hash = "6a25a2eb8fffdd349eade208643bf7f1dc155cb1df7e4e746249383de3530991"

[[files]]
file = "config/yosbr/config/xaeroworldmap-common.txt"
hash = "f02ca95d7246bd4b9c7de895c46108fff42fd5fcf9d56816b7bdba821597b58f"

[[files]]
file = "config/yosbr/config/xaeroworldmap.txt"
hash = "dcb6bfc47c4b6550e63142182649f2c4d125e0a2c2a30c1fd56cae7c3be90e52"

[[files]]
file = "config/yosbr/options.txt"
hash = "9ef66003f97aa41e58cf89b17c6a1e27567981bffac4234f9f929b120ad90852"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "9c5ffe0f93aec9ebca86a4e5171ccb51e283849eef1719c995d19c2480e2d07c"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "352fe01e3b8136cf2abf742ddc8e2cab45fd7f25f635df960053b8290e5dc2a4"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "a463f60553d19dc6cdb468e8a0f9faa73fd6694f8eb87fe11532c81e9c908dcf"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "57c157ebf3f36495fa14668c3906e70726a83564c7d0071507fc85baa106626c"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "7eec1f23021757cffb4d9cbb954da4e543cecfc5739a2b5f6d78b1ed6ea10ee6"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "dc1578a021bb4e5699524f5216d8aa9b08c9d30bfbfe0bc72bf07f5391c3f3b5"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "5dccb53650c19b933db206e676ef00f1d1d0129f6d072a53e5111421ea461cf6"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "1e77f24415a10692531a1d38f9163e52f70f0d98d9407f4f3cdee5bbef3ed03c"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "6df3e228c8d79cd14de683a5de571cf0f0fbcd412d48db463240e47b893b9a81"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "20d7b9a3333ef86d70c3b3becaeccc9ef5961c41e8cd936bb1df9cf0b946c546"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "13ae813426f52226d8363499d722df0933e84534f216eef127c198c18bcdbb6b"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "278a349024e41e039f9f4a278532b56d1774cd2f7fde04f2cff298f3e085d995"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "d3b90bf089e63af8545bfb795a4d20dc4bb52ceec87e5b632cdbfaad730bb8f6"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a90139b002d632ba9256cb3e7e877945bf8e3afa5b191d1adc83c5e3eb72da4c"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "a119aa71d4ec78d6ef21bc8c409a2e2a938d493b7f7aacfa63c0998e8d370e11"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "91c0fcd0a32565f0ad1e38d67b0db1cb5fbef2ea3ae018f2e323155997d9074a"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "f34159a6e4806f4127a6db44b859c1801ffcd37f482dd87281dc29ebbbf95806"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
hash = "4a19208b07355c3e25d8320feec6a6c254608679477a1050b110b3f68b0bdf89"
metafile = true

[[files]]
file = "mods/easy-magic.pw.toml"
hash = "8fe407d6c0edd1ab94e10b2b7f917b6c344f6f99549aad58c0783da38427a0fa"
metafile = true

[[files]]
file = "mods/easy-shulker-boxes.pw.toml"
hash = "9645ea203dba3249733227c91020016893ca223c2dbef81172560cd322603c10"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "875171917de85a936767be77f6dfa677ff3a38865dd3e6f6fbd4b776101dc350"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "058798a2c892733565bbd4b5566743b0305bdaa6d2c4237a98ec432e4cd96c4e"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "ef396a2a22ba8828f3ec54d18e721ed6f37003b0373bef1d916455eee2b602d4"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "b485baa8463264b932f798974a17f3edd963f5abe1c65da425529124a10a411a"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "528200f74061ca4d9ca1e1e65d932fd7fd49a071cef36912f117a4b2a0a537cf"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "967a780be97bec40b8bca4945a053ee4fbd05d58e218c4fb803959ac0d0c7f08"
metafile = true

[[files]]
file = "mods/fabricbettergrass.pw.toml"
hash = "eab2d8e0481dcf624b39ccfcc714e41c393690b90b89ff8d874e96fa1e47e776"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "08114da8c86093301d6b6e07349709395599c4731626058a27a5395dd6369ff4"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fbf9806c22ee5bccbe08f7dec15b742f5ae3a70caf186d6dce0d42f28790f559"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "6e572f70d25f8f509761cb13f0d29eb2f9333713e4d32b33ecd576f7545a738e"
metafile = true

[[files]]
file = "mods/fog.pw.toml"
hash = "efb219f59a3523c4be51283274932c4b07a730c34ad986e183fc1c5873e1817b"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "af10334d5cb965e4255f864d8fe2c3bad90e571492bf61fd84fb55c9a9506d59"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "2449e4f29f167ff8453e67d0d4fc47294523e2ca9dce022d1a5670cd2ed49808"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "781569b236e3803e831888850b61c9765aa031c3db3a73730586f3868b186658"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "623f91f5cb2cfe0e7c3a6fc48ae5984dfad62e85389e2567ab5421f7d9d02c51"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "8b481b1845bb190388182a683a4efe506516429ede29757923f48eba2e1a43e4"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "4f91b0b457fcd875c378c1ab161ac57fbbfb06f5a99ca97c606addb6d6daa6c4"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "9ec22a69da98cef889829ee289c8c08bff2b26c181eebd1303cd35a7ecc102f4"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "3c99ce9501ba667070c8cb9a44adfcef91b071983d3ab565acb11cca93469820"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5773d3e597b591a9cd1d6d0808aa5820ecfef9f95c3ebe88aae485980f032e8a"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "3ba523b0e2a61388644998f4ce0e34bffe2b4bbe59d5b4bd8e467e52fc4fc21a"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "732e3a5fb7d7c41c380d1ba92118293db75d5a7f2c05a6df6ac04c54c4bd1a22"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "1d19237dc3a66d87a018bafb3f69e701bcba8ba1fdef71d9a5f17222c15a3120"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "14800fc12fd4b92497c0f26455523783bdf59194233bdaa71d4864b3d436929a"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e48fadea92533a14b45d8fb64ed10e5942ee90bba874589822a766a6d47930b2"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "c71075106b0f5ddc29718d90e923c62388e4b17d741ff34a3cfa1cddaa43b86e"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "ea1d303d34de75ef3745a218e1e48fa72cc0e04265142ed27345fdede5b1d954"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "f1873dc9fe8a5cbea26ceffba3ec46098bce4eef7f4efd29ea849df9ccc2f66c"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "471861d58fcae927ae15f5df7fb436617771648ffb909d2a88e9d6e78068ff8c"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "9445550cf3fcfaaa145d60528e01c55d2fa798bcfc1232c141ddf3b94b6e0022"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "3c79199e4f8a8221ae7095f45a83655fa3baebb59e4cab3d2544be52d1b29df6"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
hash = "60839cfc3cb0ad0f4618dbe25b674ed317deecf3ae067b30913f26e8ac29df9a"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "37d94eccb60749412f669a737642a603eb549225c9a49c45320a0ca097dfc513"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "45473d5027f61ec3fe7c60e4835c6215aa12f48086d237c42bdfd34d22c90905"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "f599da7c46d2acdca321efcf35d78c53d69a73168e86344971b857bc2c754932"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "86e1d2e85c9b71d8b0d3710b04ca305aeda417656fbf86a6ea7264a5acf08dcf"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "2f7057e72af0cc31061ed60c31fce906122d0913ecbb956f124a1b35575f4b1a"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "8ff84533e8fe06943d7d72e25e9b4393837e574a5c7c9e358206294b2cb0939c"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "abe9878dcb237d56e2ba70c17db8c721c6c2b8e62b241bc333539d5bc6be938f"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "0f71a55dbe4ad9c1692cebcf1da0d69b66466a5a2a8cc9593e62b6d38021c367"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "700caca572649f238e804258f79d25969031be3e1b01d0384eb54a13200caba6"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "6e6d211a726a79c4e9ce7a82ced3c06fd61d19a5c4a583531388962930e835fd"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
hash = "7120245268837d69173477dfae3dd86f561678221c9a499317a7e2a480661173"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "24050805ccbaac24f4fc352200756b903ac7ef473d99169275b3fbb9f1ebe1b0"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "ff0d87064f466d6dfa5151178cb805cea4169a6e85f47913b462758262a78024"
metafile = true

[[files]]
file = "mods/tiny-item-animations.pw.toml"
hash = "d5f9e116bdb4df696136acac99d9a80e8d229375b5a8865ff794e603bca0b0d4"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "2fcbe0a98ff51dc54a24d983251f478c29d4d6cbe731abb3e7e002263931a317"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "d1de6d3e889db21acd36afb754f20b6ccc8c850cb7ef839047eb440e6114d652"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "bc5b833dac6b91f96e3d650e1209d141b9267ce7cb7ac45b8b5a976d6c6a5f4e"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "130159e2b3734e4013e2ad5040e6a80b14a004d75a921dc24633d906636500e8"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "3556431e076004f61282c316088b95bb99f8c26136c1f2aee4fc1577f33479dc"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "76d79c4c09c4b862ce82cc0cfee5ee4f01222c1968586ba68d9435767aecfcd8"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "resourcepacks/bettervanillabuilding.pw.toml"
hash = "7e6e789cc2bfbf4090eaae5758dc9c248b240a95aec767da77076260f4bb80e4"
metafile = true

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
hash = "93f7c611597f7291932163a18cbe7787cec376e15d655632b4bdf289dbd937af"
metafile = true

[[files]]
file = "resourcepacks/even-better-enchants.pw.toml"
hash = "3bd80b33acc0cd9392e98bdc0becad357e15895b91b4f15d3ae0c5fde613a500"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "63afe0bdced729726cdeea08c7af847d0e58d51682f093062d253adb8c795422"
metafile = true

[[files]]
file = "resourcepacks/sparkles.pw.toml"
hash = "4d1f80d4aea6f81427b67313796afa14e4319d6284ea512169243a74f7c74ba7"
metafile = true

[[files]]
file = "resourcepacks/theones-eating-animation-pack.pw.toml"
hash = "6b681263dd5446942daad11d634e9f61c847aa865486adec890d0b228da56faa"
metafile = true

[[files]]
file = "shaderpacks/ComplementaryReimagined_r5.1.1.zip.txt"
hash = "1d07ab91190d6dcff74900a3f4a56c03dc70504e7917f87eac3b685b429b0671"

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "3385e33cb8e2cbf402562dcb68669cc2905fec01b4be9fe27a516010c5aaff87"
metafile = true
